### ISSUE TITLE
It would be helpful to display current config values if new values aren't specified.

### ISSUE THREAD

**Issue by RufusVS** [BastiPaeltz/codedict#2]
for your configuration commands:
--suffix LANGUAGE SUFFIX
--editor EDITOR
If the user doesn't supply a new value, print the current value.  (I had a problem when I first
installed, because during my first "add" the editor name was incorrect.)

So I'd get:
Error calling your editor - (2): The system cannot find the file specified
(It would be good if it displayed the editor name in the error message).

then I reread the Usage: message, and found those configuration items and had this idea.

**Comment by BastiPaeltz** [comment]
Hey,

this is definately true. I added that behaviour for --editor, --suffix and --line just now. Values are now optional there. Also I made the editor error message a bit more verbose and clear. 
Thanks for contributing :)
